      services:
        app:
          build:
            context: .
          container_name: control_node_app
          ports:
            - "80:3000"
          env_file:
            - ./backend/.env
          volumes:
           - ./backend:/app
           - /app/node_modules
          depends_on:
            - db
          restart: on-failure

        db:
          image: mongo:8.0
          container_name: control_node_db
#          ports:
#            - "5555:27017"
          env_file:
            - backend/.env
          volumes:
            - mongo_data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

          restart: on-failure

      volumes:
        mongo_data:

